# Generated by Django 4.1 on 2022-09-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nhi',
            field=models.TextField(max_length=7, unique=True),
        ),
    ]
